# Static inventory.
# 'ansible_host' ke saamne apne VM ka PUBLIC IP daalo.
# IP nikalne ke liye:  terraform -chdir=envs/dev output instance_public_ips

[dev]
dev-app-01 ansible_host=92.4.89.228

[dev:vars]
ansible_user=opc
ansible_ssh_private_key_file=~/.ssh/oci_dev
